//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.Kinect.KinectFusionExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Samples.Kinect.KinectFusionExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Kinect Fusion camera tracking failed. Align the camera to the last tracked position. 的本地化字符串。
        /// </summary>
        internal static string CameraTrackingFailed {
            get {
                return ResourceManager.GetString("CameraTrackingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error saving Kinect Fusion mesh! 的本地化字符串。
        /// </summary>
        internal static string ErrorSaveMesh {
            get {
                return ResourceManager.GetString("ErrorSaveMesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fps: {0:0.00} 的本地化字符串。
        /// </summary>
        internal static string Fps {
            get {
                return ResourceManager.GetString("Fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click &quot;Near Mode&quot; to change sensor range, and &quot;Reset Reconstruction&quot; to clear 的本地化字符串。
        /// </summary>
        internal static string IntroductoryMessage {
            get {
                return ResourceManager.GetString("IntroductoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid mesh arguments. Saving mesh process aborted 的本地化字符串。
        /// </summary>
        internal static string InvalidMeshArgument {
            get {
                return ResourceManager.GetString("InvalidMeshArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create mesh of non-existent reconstruction 的本地化字符串。
        /// </summary>
        internal static string MeshNullVolume {
            get {
                return ResourceManager.GetString("MeshNullVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mesh save canceled 的本地化字符串。
        /// </summary>
        internal static string MeshSaveCanceled {
            get {
                return ResourceManager.GetString("MeshSaveCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved Kinect Fusion mesh 的本地化字符串。
        /// </summary>
        internal static string MeshSaved {
            get {
                return ResourceManager.GetString("MeshSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A prerequisite component for Kinect Fusion is missing. Please refer to the Toolkit documentation for assistance 的本地化字符串。
        /// </summary>
        internal static string MissingPrerequisite {
            get {
                return ResourceManager.GetString("MissingPrerequisite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Near mode is not supported by device 的本地化字符串。
        /// </summary>
        internal static string NearModeNotSupported {
            get {
                return ResourceManager.GetString("NearModeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No ready Kinect found! 的本地化字符串。
        /// </summary>
        internal static string NoReadyKinect {
            get {
                return ResourceManager.GetString("NoReadyKinect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out of memory error initializing reconstruction - try a smaller reconstruction volume 的本地化字符串。
        /// </summary>
        internal static string OutOfMemory {
            get {
                return ResourceManager.GetString("OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kinect Fusion reset reconstruction call failed 的本地化字符串。
        /// </summary>
        internal static string ResetFailed {
            get {
                return ResourceManager.GetString("ResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reconstruction has been reset 的本地化字符串。
        /// </summary>
        internal static string ResetVolume {
            get {
                return ResourceManager.GetString("ResetVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kinect Fusion camera tracking failed, automatically reset volume 的本地化字符串。
        /// </summary>
        internal static string ResetVolumeAuto {
            get {
                return ResourceManager.GetString("ResetVolumeAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating and saving mesh of reconstruction, please wait... 的本地化字符串。
        /// </summary>
        internal static string SavingMesh {
            get {
                return ResourceManager.GetString("SavingMesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume resolution should be greater than 0 and multiple of 32 的本地化字符串。
        /// </summary>
        internal static string VolumeResolution {
            get {
                return ResourceManager.GetString("VolumeResolution", resourceCulture);
            }
        }
    }
}
